export const GET_AUCTION_ITEMS_SUCCEEDED = 'GET_AUCTION_ITEMS_SUCCEEDED';
export const GET_AUCTION_ITEMS_FAILED = 'GET_AUCTION_ITEMS_FAILED';
export const GET_AUCTION_ITEM_BY_ID_SUCCEEDED = 'GET_AUCTION_ITEM_BY_ID_SUCCEEDED';
export const GET_AUCTION_ITEM_BY_ID_FAILED = 'GET_AUCTION_ITEM_BY_ID_FAILED';
